--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HiroshimaTeam/Unclaim-finder
build-by-default: true
branches:
- main
projects:
  Unclaim-finder:
    path: ""
    icon: logo.png
...
